// apps/vue-app/src/views/login.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();
const email = ref("");
const password = ref("");

async function handleSubmit() {
	// TODO: replace with real auth
	await router.push("/");
}
</script>

<template>
  <main class="flex flex-1 flex-col items-center justify-center">
    <div class="w-full max-w-sm space-y-4 rounded-lg border p-6">
      <h1 class="text-2xl font-bold">Login</h1>
      <form class="space-y-4" @submit.prevent="handleSubmit">
        <div class="space-y-1">
          <label class="text-sm font-medium" for="email">Email</label>
          <input
            id="email"
            v-model="email"
            class="w-full rounded-md border px-3 py-2 text-sm"
            placeholder="you@example.com"
            required
            type="email"
          />
        </div>
        <div class="space-y-1">
          <label class="text-sm font-medium" for="password">Password</label>
          <input
            id="password"
            v-model="password"
            class="w-full rounded-md border px-3 py-2 text-sm"
            placeholder="••••••••"
            required
            type="password"
          />
        </div>
        <button
          class="w-full rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700 dark:bg-gray-100 dark:text-gray-900 dark:hover:bg-gray-200"
          type="submit"
        >
          Sign in
        </button>
      </form>
    </div>
  </main>
</template>

// apps/react-app/app/routes/login/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import * as Lucide from 'lucide-react'

import { Link } from '#/components/link'

import { LoginForm } from './-form'

export const Route = createFileRoute('/login/')({
  component: LoginComponent,
})

function LoginComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50 px-4 py-12 sm:px-6 lg:px-8 dark:bg-gray-900">
      <div className="w-full max-w-md space-y-8">
        <div>
          <img
            className="mx-auto block h-12 w-auto dark:hidden"
            src="/images/logo-light.svg"
            alt="Logo"
          />
          <img
            className="mx-auto hidden h-12 w-auto dark:block"
            src="/images/logo-dark.svg"
            alt="Logo"
          />
          <h2 className="mt-6 text-center font-bold text-3xl text-gray-900 dark:text-white">
            Sign in to your account
          </h2>
          <p className="mt-2 text-center text-gray-600 text-sm dark:text-gray-400">
            Or{' '}
            <Link
              href="#"
              className="font-medium text-blue-600 hover:text-blue-500 dark:text-blue-400"
            >
              create a new account
            </Link>
          </p>
        </div>

        <LoginForm />

        <div className="mt-4 text-center">
          <Link
            href="/"
            className="text-gray-600 text-sm hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
          >
            <Lucide.ArrowLeft className="-ml-0.5 mr-1 inline-block size-4" />
            <span>Back to homepage</span>
          </Link>
        </div>
      </div>
    </div>
  )
}
