// apps/vue-app/src/views/login.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();
const email = ref("");
const password = ref("");

async function handleSubmit() {
	// TODO: replace with real auth
	await router.push("/");
}
</script>

<template>
  <main class="flex flex-1 flex-col items-center justify-center">
    <div class="w-full max-w-sm space-y-4 rounded-lg border p-6">
      <h1 class="text-2xl font-bold">Login</h1>
      <form class="space-y-4" @submit.prevent="handleSubmit">
        <div class="space-y-1">
          <label class="text-sm font-medium" for="email">Email</label>
          <input
            id="email"
            v-model="email"
            class="w-full rounded-md border px-3 py-2 text-sm"
            placeholder="you@example.com"
            required
            type="email"
          />
        </div>
        <div class="space-y-1">
          <label class="text-sm font-medium" for="password">Password</label>
          <input
            id="password"
            v-model="password"
            class="w-full rounded-md border px-3 py-2 text-sm"
            placeholder="••••••••"
            required
            type="password"
          />
        </div>
        <button
          class="w-full rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700 dark:bg-gray-100 dark:text-gray-900 dark:hover:bg-gray-200"
          type="submit"
        >
          Sign in
        </button>
      </form>
    </div>
  </main>
</template>

// apps/tanstack-start/src/routes/login.tsx
import { createFileRoute } from "@tanstack/react-router";
import * as React from "react";

export const Route = createFileRoute("/login")({
	component: LoginPage,
});

function LoginPage() {
	const [email, setEmail] = React.useState("");

	return (
		<main className="mx-auto max-w-md px-4 py-12 sm:px-6 lg:px-8">
			<h1 className="font-semibold text-3xl tracking-tight">Sign in</h1>
			<p className="mt-2 text-muted-foreground">
				Demo form only (no auth wired).
			</p>

			<form className="mt-8 rounded-xl border bg-card p-6 shadow-sm">
				<label className="block text-sm">
					<span className="text-muted-foreground">Email</span>
					<input
						value={email}
						onChange={(e) => setEmail(e.currentTarget.value)}
						type="email"
						placeholder="you@company.com"
						className="mt-2 w-full rounded-md border bg-background px-3 py-2"
					/>
				</label>

				<button
					type="button"
					className="mt-4 inline-flex w-full items-center justify-center rounded-md bg-primary px-4 py-2 font-medium text-primary-foreground"
					onClick={() => alert(`Hello, ${email || "friend"}!`)}
				>
					Continue
				</button>
			</form>
		</main>
	);
}
